Update sync.yml

diff --git a/.github/workflows/sync.yml b/.github/workflows/sync.yml
--- a/.github/workflows/sync.yml
+++ b/.github/workflows/sync.yml
@@ -55,18 +55,17 @@ jobs:
           # 打印响应内容，方便调试
           # echo "API Response: $RESPONSE"
 
-      - name: Download Release ZIP from Private Repo
-        run: |
-              curl -L -H "Authorization: token ${{ secrets.IVESTEST }}" -o Rafael-SDK-Internal-$LATEST_RELEASE.zip \
-                   https://github.com/iveslee308/Rafael-SDK-Internal/archive/refs/tags/$LATEST_RELEASE.zip)
-        
-        env:
-          GH_TOKEN: ${{ secrets.IVESTEST }} 
+          ZIP_URL="https://github.com/YOUR_USERNAME/YOUR_PRIVATE_REPO/archive/refs/tags/$TAG_NAME.zip"
+          echo "Downloading from $ZIP_URL..."
+              # 下载 Source Code ZIP
+          curl -L -H "Authorization: token ${{ secrets.PRIVATE_REPO_TOKEN }}" -o source.zip "$ZIP_URL"
 
-      - name: Extract Source Code
-        run: |
-          unzip Rafael-SDK-Internal-$LATEST_RELEASE.zip -d source_code
-          cd source_code/*
+          # 检查 ZIP 文件是否有效
+          if ! unzip -tq source.zip; then
+            echo "Error: ZIP file is invalid!"
+            exit 1
+          fi      
+
 
       #- name: Push files to public repo
       #  run: |
